# -*- coding: utf-8 -*-
"""IterTools.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1opaedBRkScNTNo4kNkmT7RPsS9cThObE
"""

from itertools import product

params = {'learning_rate': [1e-1,1e-2,1e-3],
          'batch_size': [10,20,30,40]
          }

"""Regular nested loops for different combination of paramater looping"""

for rate in params['learning_rate']:
  for size in params['batch_size']:
    comb = (rate,size)
    print(comb)

"""Optimised Itertools product for parameter looping"""

for comb in product(*params.values()):
  print(comb)

